name: WookieeItemNames
main: uk.co.chieloos.wookieeitemnames.WookieeItemNames
version: 0.3
authors: [chieloos]
website: http://dev.bukkit.org/server-mods/wookieeitemnames/
description: Item name library.